backbone:
  _target_: src.backbones.HuggingFaceBackbone
  prompt:
    _target_: src.prompts.DetailedCMGPrompt
  model_name: deepseek-ai/deepseek-coder-6.7b-instruct
  is_encoder_decoder: false
  model_kwargs:
    torch_dtype: auto
    device_map: auto
    load_in_8bit: false
    load_in_4bit: false
    attn_implementation: flash_attention_2
  generation:
    do_sample: true
    temperature: 0.8
    max_length: null
    max_new_tokens: 512
  device: cuda
  seed: 2687987020
  use_bettertransformer: false
preprocessor:
  _target_: src.preprocessors.SimpleCMGPreprocessor
  include_path: true
logger:
  use_wandb: true
  name: deepseek-coder-6.7b_detailed
  project: cmg
  local_artifact: false
data_src:
  _target_: src.data_sources.HFDataSource
  cache_dir: null
  hub_name: icmlbenchname/commit-message-generation
  configs:
  - default
  split: test
