hydra:
  job:
    name: ${backbone.name}_nltk_emb
  run:
    dir: /home/tigina/lca-baselines/bug_localization/output/${hydra:job.name}
  job_logging:
    root:
      handlers: [console, file]
backbone:
  _target_: src.baselines.backbones.emb.tfidf_emb_backbone.TfIdfEmbBackbone
  name: tfidf
  pretrained_path: null
  tokenizer:
    _target_: src.baselines.backbones.emb.tokenizers.nltk_tokenizer.NltkTokenizer
  ranker:
    _target_: src.baselines.backbones.emb.rankers.cosine_distance_ranker.CosineDistanceRanker
data_source:
  _target_: src.baselines.data_sources.hf_data_source.HFDataSource
  cache_dir: null
  repos_dir:  /mnt/data/shared-data/lca/repos_updated
  hub_name: tiginamaria/bug-localization
  configs:
    - py
    - java
    - kt
  split: test