backbone:
  _target_: src.backbones.OpenAIBackbone
  prompt:
    _target_: src.prompts.DetailedCMGPromptForFullFiles
  model_name: o1-mini-2024-09-12
  api_key: null
  parameters:
    temperature: 0.8
preprocessor:
  _target_: src.preprocessors.LoadFromDatasetPreprocessor
  include_path: true
  hf_repo_id: "icmlbenchname/commit-message-generation"
  hf_repo_config: "full_files"
  hf_repo_split: "16k"
logger:
  use_wandb: false
  name: null
  project: null
  local_artifact: null
data_src:
  _target_: src.data_sources.HFDataSource
  cache_dir: null
  hub_name: icmlbenchname/commit-message-generation
  configs:
  - default
  split: test
