hf_api_key: "pattern"
hf_tokenizer_checkpoint: "meta-llama/Llama-2-7b-chat-hf"
api_key: "pattern"
model_name: "gpt-4-turbo-2024-04-09"
logs_dir: "./logs"
save_dir: "./predictions-chatgpt4-1k"
max_context_toks: 1000