hf_api_key: "YOUR_KEY_HERE"
hf_tokenizer_checkpoint: "meta-llama/Llama-2-7b-chat-hf"
api_key: "YOUR_KEY_HERE"
model_name: "gpt-3.5-turbo-0125"
logs_dir: "./logs"
save_dir: "./predictions-chatgpt3-2k"
max_context_toks: 2000